import Menu from '@components/menu';
import { type Metadata } from 'next';
import Link from 'next/link';
import './globals.css';
import './layout.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="f4y__nav">
          <div className="f4y__nav__container">
            <div className="f4y__nav__container__logobar">
              <img
                className="f4y__nav__container__logobar__logo"
                src="/images/logo.png"
                alt="logo"
              />
            </div>
            <Menu />
          </div>
        </header>
        <div className="f4y__body__scroll">
          {children}
          <footer className="f4y__footer">
            <div className="f4y__footer__container">
              <img
                className="f4y__footer__container__logo"
                src="/images/logo.png"
                alt="logo"
              />
              <div className="f4y__footer__container__links">
                <div className="f4y__footer__container__links__item">
                  <h3>关于</h3>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#home">公司介绍</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#brand">品牌理念</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#team">团队介绍</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#fun4lab">最新公告</Link>
                  </div>
                </div>
                <div className="f4y__footer__container__links__item">
                  <h3>关于产品</h3>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#home">作品展示</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#brand">在线商城</Link>
                  </div>
                </div>
                <div className="f4y__footer__container__links__item">
                  <h3>资源</h3>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#home">IP LIBRARY</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#brand">设计师和合作招募</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#team">Ant Cool</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#fun4lab">AntD Library</Link>
                  </div>
                </div>
                <div className="f4y__footer__container__links__item">
                  <h3>关注</h3>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#home">FUN4YEAH</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#brand">FUN4YEAH</Link>
                  </div>
                  <div className="f4y__footer__container__links__item__row">
                    <Link href="/#team">FUN4YEAH</Link>
                  </div>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
